services:
  - type: web
    name: gopark-py
    env: python
    plan: starter  # Upgrade to starter plan for more memory (512MB -> 1GB)
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000